services:
  # Backend API service
  - type: web
    name: learning-compass-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # You'll need to add your ANTHROPIC_API_KEY in Render dashboard

  # Frontend static site
  - type: static
    name: learning-compass-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html